config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :users, except: :index

  resources :sessions, only: :create
  get "sign_in", to: "sessions#new", as: "sign_in"
  delete "sign_out", to: "sessions#destroy", as: "sign_out"

  resources :posts

  resources :comments, only: %i( destroy )

  post "likes/:likeable_type/:likeable_id", to: "likes#create", as: :likes
  delete "likes/:id", to: "likes#destroy", as: :like

  post "follows/:followed_id", to: "follows#create", as: :follows
  delete "follows/:followed_id", to: "follows#destroy", as: :follow
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable

  belongs_to :post, counter_cache: true
  belongs_to :author, class_name: "User"
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower,
    class_name: "User",
    counter_cache: :followings_count

  belongs_to :followed,
    class_name: "User",
    counter_cache: :followers_count
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :likeable, polymorphic: true, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
  include Likeable

  belongs_to :author, class_name: "User"

  has_many :comments, -> { includes(:author, :likes).order(created_at: :asc) },
    dependent: :destroy

  accepts_nested_attributes_for :comments

  attribute :youtube_url, YouTubeURLType.new
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :follows_as_follower,
    class_name: "Follow",
    foreign_key: "follower_id",
    counter_cache: :followings_count,
    dependent: :destroy

  has_many :follows_as_followed,
    class_name: "Follow",
    foreign_key: "followed_id",
    counter_cache: :followers_count,
    dependent: :destroy

  has_many :followers,
    through: :follows_as_followed,
    dependent: :destroy

  has_many :followings,
    through: :follows_as_follower,
    source: :followed,
    dependent: :destroy

  has_many :posts,
    foreign_key: "author_id",
    dependent: :destroy

  has_many :comments,
    foreign_key: "author_id",
    dependent: :destroy

  has_many :likes,
    foreign_key: "author_id",
    dependent: :destroy

  validates :username, presence: true

  def likes?(likeable)
    likes = likeable.likes.to_a

    likes.find { |like| like.author == self }
  end

  def follows?(user)
    followings.to_a.find do |following|
      following == user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Redirection
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def destroy
    comment = Comment.find(params[:id])
    post    = comment.post

    comment.destroy

    redirect_to post
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    followed = User.find(params[:followed_id])

    Current.user.followings << followed

    redirect_back_or_to followed
  end

  def destroy
    followed = User.find(params[:followed_id])
    follow   = Follow.find_by(follower: Current.user, followed: followed)

    follow.destroy

    redirect_back_or_to followed
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @posts = Post.includes(:author).order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    likeable_class = params[:likeable_type].constantize
    likeable       = likeable_class.find(params[:likeable_id])
    likes          = likeable.likes

    likes.create(author: Current.user)

    redirect_back_to_anchor likeable, fallback_location: likeable
  end

  def destroy
    like     = Like.find(params[:id])
    likeable = like.likeable

    like.destroy

    redirect_back_to_anchor likeable, fallback_location: likeable
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])

    detect_editable_comment
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(**post_params, author: Current.user)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      if @post.author == Current.user
        redirect_back_or_to edit_post_path(@post)
      else
        redirect_back_or_to @post
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to root_url
  end

  private
    def post_params
      params.require(:post).permit(:id, :media_url, :youtube_url, :title, :content, comments_attributes: [:id, :content, :author_id])
    end

    def detect_editable_comment
      if params[:editable_comment_id] && (comment = Comment.find(params[:editable_comment_id]))
        if (comment.post == @post) && (comment.author == Current.user)
          @editable_comment = comment
        end
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate, except: %i( new create )

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_username(user_params[:username])

    if @user && @user.authenticate(user_params[:password])
      cookies.encrypted[:user_id] = @user.id

      redirect_to root_url
    else
      User.new(user_params).tap do |invalid_user|
        invalid_user.validate

        errors = invalid_user.errors.full_messages << "Wrong username or password"

        redirect_to sign_in_path, flash: { errors: errors }
      end
    end
  end

  def destroy
    if cookies.encrypted[:user_id] == Current.user.id
      cookies.encrypted[:user_id] = nil

      Current.user = nil
    end

    redirect_to sign_in_path
  end

  private
    def user_params
      params.permit(:username, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i( new create )

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      cookies.encrypted[:user_id] = @user.id

      redirect_to root_url
    else
      redirect_to new_user_path, flash: { errors: @user.errors.full_messages }
    end
  end

  def update
    @user = User.find_by(id: params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])

    @user.destroy

    redirect_to new_user_path
  end

  private
    def user_params
      params.require(:user).permit(:id, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def redirect_to_path
    "#{request.full_path}##{dom_id(likeable)}"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" class="flex flex-col p-4 shadow gap-4 target:border">
  <% if comment == @editable_comment %>
    <%= render "comments/form", comment: comment %>
  <% else %>
    <% if comment.author == Current.user %>
      <div class="flex justify-end gap-4">
        <%= link_to "Edit", post_path(comment.post, editable_comment_id: comment.id), class: "link" %>
        <%= button_to "Delete", comment, method: :delete, class: "link" %>
      </div>
    <% end %>

    <div class="flex gap-2">
      <span>
        <%= link_to comment.author.username, comment.author, class: "font-bold link" %>
      </span>
      <span>
        <%= comment.created_at %>
      </span>
      <span>
        <%= comment.updated_at %>
      </span>
    </div>

    <p>
      <%= comment.content %>
    </p>

    <%= render "shared/like_button", likeable: comment %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: comment.post do |post_form| %>
  <%= post_form.fields_for :comments, comment do |comment_form| %>
    <%= comment_form.hidden_field :author_id %>

    <div class="flex flex-col gap-2">
      <%= comment_form.text_area :content, class: "rounded" %>
      <%= comment_form.submit class: "flex self-end" %>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= content_for :meta do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>

<%= form_with model: @post do |post_form| %>
  <div class="flex flex-col gap-4 w-fit">
    <div class="flex flex-col">
      <%= post_form.label :media_url, "Upload a picture" %>
      <%= post_form.hidden_field :media_url, class: "simple-file-upload", "data-turbo": false %>
    </div>

    <p>Or...</p>

    <div class="flex flex-col">
      <%= post_form.label :youtube_url, "Share a YouTube URL" %>
      <%= post_form.url_field :youtube_url, placeholder: "https://www.youtube.com/watch?v=BnK9oeBI9G4" %>
    </div>

    <div class="flex flex-col">
      <%= post_form.label :title %>
      <%= post_form.text_field :title %>
    </div>

    <div class="flex flex-col">
      <%= post_form.label :content %>
      <%= post_form.text_area :content %>
    </div>

    <div class="flex self-end">
      <%= post_form.submit "Post" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class="flex flex-col p-4 rounded shadow gap-4 target:border">
  <div>
    <% if post.author == Current.user %>
      <div class="flex justify-end gap-4">
        <%= link_to "Edit", edit_post_path(post), class: "link" %>
        <%= button_to "Delete", post, method: :delete, class: "link" %>
      </div>
    <% end %>

    <span>
      <%= link_to post.author.username, post.author, class: "font-bold link" %>
    </span>

    <span>
      <%= post.created_at %>
    </span>
  </div>

  <% if post.youtube_url %>
    <iframe src="<%= post.youtube_url %>" height="315" frameborder="0"></iframe>
  <% else %>
    <% if post.media_url %>
      <%= image_tag post.media_url %>
    <% end %>
  <% end %>

  <h2>
    <%= link_to post.title, post, class: "font-bold link" %>
  </h2>

  <p>
    <%= post.content %>
  </p>

  <div class="flex items-center justify-between">
    <%= render "shared/like_button", likeable: post %>
    <%= link_to "#{post.comments.size} comments", post_path(post, anchor: "comments"), class: "link" %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div>
  <%= render @post %>

  <div id="comments" class="flex flex-col p-4 gap-4">
    <%= render @post.comments %>
    <%= render "comments/form", comment: @post.comments.build(author: Current.user) %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user do |user_form| %>
  <div class="flex flex-col items-end w-fit gap-4">
    <div>
      <%= user_form.label :username %>
      <%= user_form.text_field :username %>
    </div>

    <div>
      <%= user_form.label :password %>
      <%= user_form.password_field :password %>
    </div>

    <div>
      <%= user_form.label :password_confirmation, "Confirmation" %>
      <%= user_form.password_field :password_confirmation %>
    </div>

    <% unless @user.persisted?  %>
      <%= user_form.submit "Sign up" %>

      <p>
        Already have an account ? <%= link_to "Sign in", sign_in_path %>
      </p>
    <% else %>
      <%= user_form.submit %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile informations</h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render "form" %>

app/views/users/show.html.erb
<div class="flex items-center gap-4">
  <h1>
    <%= @user.username %>
  </h1>

  <% unless @user == Current.user  %>
    <% if Current.user.follows? @user %>
      <%= button_to "Unfollow", follow_path(@user), method: :delete %>
    <% else %>
      <%= button_to "Follow", follows_path(@user) %>
    <% end %>
  <% end %>

  <span>
    Followers <%= @user.followers.size %>
  </span>

  <span>
    Followings <%= @user.followings.size %>
  </span>
</div>