config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :users, except: :index

  resources :sessions, only: :create
  get "sign_in", to: "sessions#new", as: "sign_in"
  delete "sign_out", to: "sessions#destroy", as: "sign_out"

  resources :posts

  resources :comments, only: %i( destroy )

  post "likes/:likeable_type/:likeable_id", to: "likes#create", as: :likes
  delete "likes/:id", to: "likes#destroy", as: :like

  post "follows/:followed_id", to: "follows#create", as: :follows
  delete "follows/:followed_id", to: "follows#destroy", as: :follow
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable

  belongs_to :post, counter_cache: true
  belongs_to :author, class_name: "User"
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower,
    class_name: "User",
    counter_cache: :followings_count

  belongs_to :followed,
    class_name: "User",
    counter_cache: :followers_count
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :likeable, polymorphic: true, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
  include Likeable

  belongs_to :author, class_name: "User"

  has_many :comments, -> { includes(:author, :likes).order(created_at: :asc) },
    dependent: :destroy

  accepts_nested_attributes_for :comments

  attribute :youtube_url, YouTubeURLType.new
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :follows_as_follower,
    class_name: "Follow",
    foreign_key: "follower_id",
    counter_cache: :followings_count,
    dependent: :destroy

  has_many :follows_as_followed,
    class_name: "Follow",
    foreign_key: "followed_id",
    counter_cache: :followers_count,
    dependent: :destroy

  has_many :followers,
    through: :follows_as_followed,
    dependent: :destroy

  has_many :followings,
    through: :follows_as_follower,
    source: :followed,
    dependent: :destroy

  has_many :posts,
    foreign_key: "author_id",
    dependent: :destroy

  has_many :comments,
    foreign_key: "author_id",
    dependent: :destroy

  has_many :likes,
    foreign_key: "author_id",
    dependent: :destroy

  validates :username, presence: true

  def likes?(likeable)
    likes = likeable.likes.to_a

    likes.find { |like| like.author == self }
  end

  def follows?(user)
    followings.to_a.find do |following|
      following == user
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    followed = User.find(params[:followed_id])

    Current.user.followings << followed

    redirect_back_or_to followed
  end

  def destroy
    followed = User.find(params[:followed_id])
    follow   = Follow.find_by(follower: Current.user, followed: followed)

    follow.destroy

    redirect_back_or_to followed
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @posts = Post.includes(:author).order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    likeable_class = params[:likeable_type].constantize
    likeable       = likeable_class.find(params[:likeable_id])
    likes          = likeable.likes

    likes.create(author: Current.user)

    redirect_back_to_anchor likeable, fallback_location: likeable
  end

  def destroy
    like     = Like.find(params[:id])
    likeable = like.likeable

    like.destroy

    redirect_back_to_anchor likeable, fallback_location: likeable
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])

    detect_editable_comment
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(**post_params, author: Current.user)

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      if @post.author == Current.user
        redirect_back_or_to edit_post_path(@post)
      else
        redirect_back_or_to @post
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to root_url
  end

  private
    def post_params
      params.require(:post).permit(:id, :media_url, :youtube_url, :title, :content, comments_attributes: [:id, :content, :author_id])
    end

    def detect_editable_comment
      if params[:editable_comment_id] && (comment = Comment.find(params[:editable_comment_id]))
        if (comment.post == @post) && (comment.author == Current.user)
          @editable_comment = comment
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i( new create )

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      cookies.encrypted[:user_id] = @user.id

      redirect_to root_url
    else
      redirect_to new_user_path, flash: { errors: @user.errors.full_messages }
    end
  end

  def update
    @user = User.find_by(id: params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])

    @user.destroy

    redirect_to new_user_path
  end

  private
    def user_params
      params.require(:user).permit(:id, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def redirect_to_path
    "#{request.full_path}##{dom_id(likeable)}"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YetAnotherInstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= yield :meta %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://app.simplefileupload.com/buckets/#{ENV["SIMPLE_FILE_UPLOAD_KEY"]}.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="p-4">
    <% if Current.user  %>
      <div class="flex items-center justify-between">
        <div>
          <%= link_to root_url do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" width="24" height="24"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M575.8 255.5C575.8 273.5 560.8 287.6 543.8 287.6H511.8L512.5 447.7C512.5 450.5 512.3 453.1 512 455.8V472C512 494.1 494.1 512 472 512H456C454.9 512 453.8 511.1 452.7 511.9C451.3 511.1 449.9 512 448.5 512H392C369.9 512 352 494.1 352 472V384C352 366.3 337.7 352 320 352H256C238.3 352 224 366.3 224 384V472C224 494.1 206.1 512 184 512H128.1C126.6 512 125.1 511.9 123.6 511.8C122.4 511.9 121.2 512 120 512H104C81.91 512 64 494.1 64 472V360C64 359.1 64.03 358.1 64.09 357.2V287.6H32.05C14.02 287.6 0 273.5 0 255.5C0 246.5 3.004 238.5 10.01 231.5L266.4 8.016C273.4 1.002 281.4 0 288.4 0C295.4 0 303.4 2.004 309.5 7.014L564.8 231.5C572.8 238.5 576.9 246.5 575.8 255.5L575.8 255.5z"/></svg>
          <% end %>
        </div>

        <div class="flex mr-4 gap-4">
          <%= link_to user_path(Current.user) do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="24", height="24"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M256 0C114.6 0 0 114.6 0 256s114.6 256 256 256s256-114.6 256-256S397.4 0 256 0zM256 128c39.77 0 72 32.24 72 72S295.8 272 256 272c-39.76 0-72-32.24-72-72S216.2 128 256 128zM256 448c-52.93 0-100.9-21.53-135.7-56.29C136.5 349.9 176.5 320 224 320h64c47.54 0 87.54 29.88 103.7 71.71C356.9 426.5 308.9 448 256 448z"/></svg>
          <% end %>

          <%= button_to "Sign out", sign_out_path, method: :delete %>
          <%= button_to "Delete account", Current.user, method: :delete %>
        </div>
      </div>
    <% end %>

    <div class="p-8 mx-auto my-0 md:w-1/2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_like_button.html.erb
<div class="flex gap-1">
  <% if Current.user.likes? likeable %>
    <%= button_to like_path(likeable.find_like_by_author(Current.user)), method: :delete do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="24" height="24"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M0 190.9V185.1C0 115.2 50.52 55.58 119.4 44.1C164.1 36.51 211.4 51.37 244 84.02L256 96L267.1 84.02C300.6 51.37 347 36.51 392.6 44.1C461.5 55.58 512 115.2 512 185.1V190.9C512 232.4 494.8 272.1 464.4 300.4L283.7 469.1C276.2 476.1 266.3 480 256 480C245.7 480 235.8 476.1 228.3 469.1L47.59 300.4C17.23 272.1 .0003 232.4 .0003 190.9L0 190.9z"/></svg>
    <% end %>
  <% else %>
    <%= button_to likes_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id) do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="24" height="24"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M244 84L255.1 96L267.1 84.02C300.6 51.37 347 36.51 392.6 44.1C461.5 55.58 512 115.2 512 185.1V190.9C512 232.4 494.8 272.1 464.4 300.4L283.7 469.1C276.2 476.1 266.3 480 256 480C245.7 480 235.8 476.1 228.3 469.1L47.59 300.4C17.23 272.1 0 232.4 0 190.9V185.1C0 115.2 50.52 55.58 119.4 44.1C164.1 36.51 211.4 51.37 244 84C243.1 84 244 84.01 244 84L244 84zM255.1 163.9L210.1 117.1C188.4 96.28 157.6 86.4 127.3 91.44C81.55 99.07 48 138.7 48 185.1V190.9C48 219.1 59.71 246.1 80.34 265.3L256 429.3L431.7 265.3C452.3 246.1 464 219.1 464 190.9V185.1C464 138.7 430.4 99.07 384.7 91.44C354.4 86.4 323.6 96.28 301.9 117.1L255.1 163.9z"/></svg>
    <% end %>
  <% end %>

  <span class="flex items-end text-sm">
    <%= likeable.likes.size %>
  </span>
</div>